### ISSUE TITLE
Move counter is increasing when user is not moving

### ISSUE THREAD

**Issue by flagoon** [itaditya/collect-squares-game#4]
When the user's next move is impossible (hitting the wall), he is not "moving" therefore move counter shouldn't increase.

Also, when the game is finished, the counter shouldn't increase on keystroke.

**Comment by itaditya** [comment]
Nice catch, you should get a :1st_place_medal:

**Comment by itaditya** [comment]
> When the user's next move is impossible (hitting the wall), he is not "moving" therefore move counter shouldn't increase.

Fixed in https://github.com/itaditya/collect-squares-game/pull/6

**Comment by itaditya** [comment]
@flagoon thank you so much for finding these bugs. Do let me know if you find more of these
